INSERT INTO rentprog_car_states_snapshot (
  branch_id, rentprog_id, car_name, code, number, vin, color, year, transmission,
  fuel, car_type, car_class, active, state, tank_state, clean_state, mileage,
  tire_type, tire_size, last_inspection, deposit, price_hour, hourly_deposit,
  monthly_deposit, investor_id, purchase_price, purchase_date, age_limit,
  driver_year_limit, franchise, max_fine, repair_cost, is_air, climate_control,
  parktronic, parktronic_camera, heated_seats, audio_system, usb_system,
  rain_sensor, engine_capacity, number_doors, tank_value, pts,
  registration_certificate, body_number, data, fetched_at
)
SELECT
  CASE WHEN data->>'branch_id' IS NULL OR data->>'branch_id' = 'null' OR data->>'branch_id' = '' THEN NULL ELSE (data->>'branch_id')::uuid END,
  NULLIF(data->>'rentprog_id', 'null'),
  NULLIF(data->>'car_name', 'null'),
  NULLIF(data->>'code', 'null'),
  NULLIF(data->>'number', 'null'),
  NULLIF(data->>'vin', 'null'),
  NULLIF(data->>'color', 'null'),
  CASE WHEN data->>'year' IS NULL OR data->>'year' = 'null' OR data->>'year' = '' THEN NULL ELSE (data->>'year')::integer END,
  NULLIF(data->>'transmission', 'null'),
  NULLIF(data->>'fuel', 'null'),
  NULLIF(data->>'car_type', 'null'),
  NULLIF(data->>'car_class', 'null'),
  CASE WHEN data->>'active' IS NULL OR data->>'active' = 'null' OR data->>'active' = '' THEN NULL ELSE (data->>'active')::boolean END,
  NULLIF(data->>'state', 'null'),
  CASE WHEN data->>'tank_state' IS NULL OR data->>'tank_state' = 'null' OR data->>'tank_state' = '' THEN NULL ELSE (data->>'tank_state')::boolean END,
  CASE WHEN data->>'clean_state' IS NULL OR data->>'clean_state' = 'null' OR data->>'clean_state' = '' THEN NULL ELSE (data->>'clean_state')::boolean END,
  CASE WHEN data->>'mileage' IS NULL OR data->>'mileage' = 'null' OR data->>'mileage' = '' THEN NULL ELSE (data->>'mileage')::integer END,
  CASE WHEN data->>'tire_type' IS NULL OR data->>'tire_type' = 'null' OR data->>'tire_type' = '' THEN NULL ELSE (data->>'tire_type')::integer END,
  NULLIF(data->>'tire_size', 'null'),
  NULLIF(data->>'last_inspection', 'null'),
  CASE WHEN data->>'deposit' IS NULL OR data->>'deposit' = 'null' OR data->>'deposit' = '' THEN NULL ELSE (data->>'deposit')::bigint END,
  CASE WHEN data->>'price_hour' IS NULL OR data->>'price_hour' = 'null' OR data->>'price_hour' = '' THEN NULL ELSE (data->>'price_hour')::bigint END,
  CASE WHEN data->>'hourly_deposit' IS NULL OR data->>'hourly_deposit' = 'null' OR data->>'hourly_deposit' = '' THEN NULL ELSE (data->>'hourly_deposit')::bigint END,
  CASE WHEN data->>'monthly_deposit' IS NULL OR data->>'monthly_deposit' = 'null' OR data->>'monthly_deposit' = '' THEN NULL ELSE (data->>'monthly_deposit')::bigint END,
  CASE WHEN data->>'investor_id' IS NULL OR data->>'investor_id' = 'null' OR data->>'investor_id' = '' THEN NULL ELSE (data->>'investor_id')::bigint END,
  CASE WHEN data->>'purchase_price' IS NULL OR data->>'purchase_price' = 'null' OR data->>'purchase_price' = '' THEN NULL ELSE (data->>'purchase_price')::bigint END,
  NULLIF(data->>'purchase_date', 'null'),
  CASE WHEN data->>'age_limit' IS NULL OR data->>'age_limit' = 'null' OR data->>'age_limit' = '' THEN NULL ELSE (data->>'age_limit')::bigint END,
  CASE WHEN data->>'driver_year_limit' IS NULL OR data->>'driver_year_limit' = 'null' OR data->>'driver_year_limit' = '' THEN NULL ELSE (data->>'driver_year_limit')::bigint END,
  CASE WHEN data->>'franchise' IS NULL OR data->>'franchise' = 'null' OR data->>'franchise' = '' THEN NULL ELSE (data->>'franchise')::integer END,
  CASE WHEN data->>'max_fine' IS NULL OR data->>'max_fine' = 'null' OR data->>'max_fine' = '' THEN NULL ELSE (data->>'max_fine')::integer END,
  CASE WHEN data->>'repair_cost' IS NULL OR data->>'repair_cost' = 'null' OR data->>'repair_cost' = '' THEN NULL ELSE (data->>'repair_cost')::integer END,
  CASE WHEN data->>'is_air' IS NULL OR data->>'is_air' = 'null' OR data->>'is_air' = '' THEN NULL ELSE (data->>'is_air')::boolean END,
  CASE WHEN data->>'climate_control' IS NULL OR data->>'climate_control' = 'null' OR data->>'climate_control' = '' THEN NULL ELSE (data->>'climate_control')::boolean END,
  CASE WHEN data->>'parktronic' IS NULL OR data->>'parktronic' = 'null' OR data->>'parktronic' = '' THEN NULL ELSE (data->>'parktronic')::boolean END,
  CASE WHEN data->>'parktronic_camera' IS NULL OR data->>'parktronic_camera' = 'null' OR data->>'parktronic_camera' = '' THEN NULL ELSE (data->>'parktronic_camera')::boolean END,
  CASE WHEN data->>'heated_seats' IS NULL OR data->>'heated_seats' = 'null' OR data->>'heated_seats' = '' THEN NULL ELSE (data->>'heated_seats')::boolean END,
  CASE WHEN data->>'audio_system' IS NULL OR data->>'audio_system' = 'null' OR data->>'audio_system' = '' THEN NULL ELSE (data->>'audio_system')::boolean END,
  CASE WHEN data->>'usb_system' IS NULL OR data->>'usb_system' = 'null' OR data->>'usb_system' = '' THEN NULL ELSE (data->>'usb_system')::boolean END,
  CASE WHEN data->>'rain_sensor' IS NULL OR data->>'rain_sensor' = 'null' OR data->>'rain_sensor' = '' THEN NULL ELSE (data->>'rain_sensor')::boolean END,
  NULLIF(data->>'engine_capacity', 'null'),
  CASE WHEN data->>'number_doors' IS NULL OR data->>'number_doors' = 'null' OR data->>'number_doors' = '' THEN NULL ELSE (data->>'number_doors')::integer END,
  CASE WHEN data->>'tank_value' IS NULL OR data->>'tank_value' = 'null' OR data->>'tank_value' = '' THEN NULL ELSE (data->>'tank_value')::integer END,
  NULLIF(data->>'pts', 'null'),
  NULLIF(data->>'registration_certificate', 'null'),
  NULLIF(data->>'body_number', 'null'),
  data->'data',
  NOW()
FROM (SELECT '{{ JSON.stringify($json).replace(/'/g, "''") }}'::jsonb AS data) AS j
ON CONFLICT ON CONSTRAINT rentprog_car_states_snapshot_pkey DO UPDATE SET
  branch_id = COALESCE(EXCLUDED.branch_id, rentprog_car_states_snapshot.branch_id),
  car_name = COALESCE(EXCLUDED.car_name, rentprog_car_states_snapshot.car_name),
  code = COALESCE(EXCLUDED.code, rentprog_car_states_snapshot.code),
  number = COALESCE(EXCLUDED.number, rentprog_car_states_snapshot.number),
  vin = COALESCE(EXCLUDED.vin, rentprog_car_states_snapshot.vin),
  color = COALESCE(EXCLUDED.color, rentprog_car_states_snapshot.color),
  year = COALESCE(EXCLUDED.year, rentprog_car_states_snapshot.year),
  transmission = COALESCE(EXCLUDED.transmission, rentprog_car_states_snapshot.transmission),
  fuel = COALESCE(EXCLUDED.fuel, rentprog_car_states_snapshot.fuel),
  car_type = COALESCE(EXCLUDED.car_type, rentprog_car_states_snapshot.car_type),
  car_class = COALESCE(EXCLUDED.car_class, rentprog_car_states_snapshot.car_class),
  active = COALESCE(EXCLUDED.active, rentprog_car_states_snapshot.active),
  state = COALESCE(EXCLUDED.state, rentprog_car_states_snapshot.state),
  tank_state = COALESCE(EXCLUDED.tank_state, rentprog_car_states_snapshot.tank_state),
  clean_state = COALESCE(EXCLUDED.clean_state, rentprog_car_states_snapshot.clean_state),
  mileage = COALESCE(EXCLUDED.mileage, rentprog_car_states_snapshot.mileage),
  tire_type = COALESCE(EXCLUDED.tire_type, rentprog_car_states_snapshot.tire_type),
  tire_size = COALESCE(EXCLUDED.tire_size, rentprog_car_states_snapshot.tire_size),
  last_inspection = COALESCE(EXCLUDED.last_inspection, rentprog_car_states_snapshot.last_inspection),
  deposit = COALESCE(EXCLUDED.deposit, rentprog_car_states_snapshot.deposit),
  price_hour = COALESCE(EXCLUDED.price_hour, rentprog_car_states_snapshot.price_hour),
  hourly_deposit = COALESCE(EXCLUDED.hourly_deposit, rentprog_car_states_snapshot.hourly_deposit),
  monthly_deposit = COALESCE(EXCLUDED.monthly_deposit, rentprog_car_states_snapshot.monthly_deposit),
  investor_id = COALESCE(EXCLUDED.investor_id, rentprog_car_states_snapshot.investor_id),
  purchase_price = COALESCE(EXCLUDED.purchase_price, rentprog_car_states_snapshot.purchase_price),
  purchase_date = COALESCE(EXCLUDED.purchase_date, rentprog_car_states_snapshot.purchase_date),
  age_limit = COALESCE(EXCLUDED.age_limit, rentprog_car_states_snapshot.age_limit),
  driver_year_limit = COALESCE(EXCLUDED.driver_year_limit, rentprog_car_states_snapshot.driver_year_limit),
  franchise = COALESCE(EXCLUDED.franchise, rentprog_car_states_snapshot.franchise),
  max_fine = COALESCE(EXCLUDED.max_fine, rentprog_car_states_snapshot.max_fine),
  repair_cost = COALESCE(EXCLUDED.repair_cost, rentprog_car_states_snapshot.repair_cost),
  is_air = COALESCE(EXCLUDED.is_air, rentprog_car_states_snapshot.is_air),
  climate_control = COALESCE(EXCLUDED.climate_control, rentprog_car_states_snapshot.climate_control),
  parktronic = COALESCE(EXCLUDED.parktronic, rentprog_car_states_snapshot.parktronic),
  parktronic_camera = COALESCE(EXCLUDED.parktronic_camera, rentprog_car_states_snapshot.parktronic_camera),
  heated_seats = COALESCE(EXCLUDED.heated_seats, rentprog_car_states_snapshot.heated_seats),
  audio_system = COALESCE(EXCLUDED.audio_system, rentprog_car_states_snapshot.audio_system),
  usb_system = COALESCE(EXCLUDED.usb_system, rentprog_car_states_snapshot.usb_system),
  rain_sensor = COALESCE(EXCLUDED.rain_sensor, rentprog_car_states_snapshot.rain_sensor),
  engine_capacity = COALESCE(EXCLUDED.engine_capacity, rentprog_car_states_snapshot.engine_capacity),
  number_doors = COALESCE(EXCLUDED.number_doors, rentprog_car_states_snapshot.number_doors),
  tank_value = COALESCE(EXCLUDED.tank_value, rentprog_car_states_snapshot.tank_value),
  pts = COALESCE(EXCLUDED.pts, rentprog_car_states_snapshot.pts),
  registration_certificate = COALESCE(EXCLUDED.registration_certificate, rentprog_car_states_snapshot.registration_certificate),
  body_number = COALESCE(EXCLUDED.body_number, rentprog_car_states_snapshot.body_number),
  data = COALESCE(EXCLUDED.data, rentprog_car_states_snapshot.data),
  fetched_at = NOW();

