INSERT INTO cars (
  id,
  branch_id,
  rentprog_id,
  car_name,
  code,
  number,
  vin,
  color,
  year,
  transmission,
  fuel,
  car_type,
  car_class,
  active,
  state,
  tank_state,
  clean_state,
  mileage,
  tire_type,
  tire_size,
  last_inspection,
  deposit,
  price_hour,
  hourly_deposit,
  monthly_deposit,
  investor_id,
  purchase_price,
  purchase_date,
  age_limit,
  driver_year_limit,
  franchise,
  max_fine,
  repair_cost,
  is_air,
  climate_control,
  parktronic,
  parktronic_camera,
  heated_seats,
  audio_system,
  usb_system,
  rain_sensor,
  engine_capacity,
  number_doors,
  tank_value,
  pts,
  registration_certificate,
  body_number,
  data
) VALUES (
  gen_random_uuid(),
  '277eaada-1428-4c04-9cd7-5e614e43bedc',
  '47192',
  'Chevrolet Malibu',
  'Malibu 235',
  'TH235TH',
  '1G1ZB5STXHF279609',
  'GREY',
  2017,
  'Автомат',
  'Бензин 95',
  'Седан',
  'Средний',
  true,
  1,
  false,
  true,
  132985,
  2,
  '225/50 R17',
  NULL,
  270,
  22,
  270,
  270,
  776,
  16890,
  '2024-05-14',
  21,
  1,
  540,
  25,
  300,
  false,
  false,
  false,
  true,
  false,
  true,
  false,
  false,
  '1.5',
  4,
  60,
  'Tbilisi / თბილისი',
  'AJA3667721',
  '510067133012,937590992172',
  '{}'
)
ON CONFLICT (rentprog_id) DO UPDATE SET
  branch_id = EXCLUDED.branch_id,
  car_name = EXCLUDED.car_name,
  code = EXCLUDED.code,
  number = EXCLUDED.number,
  vin = EXCLUDED.vin,
  color = EXCLUDED.color,
  year = EXCLUDED.year,
  transmission = EXCLUDED.transmission,
  fuel = EXCLUDED.fuel,
  car_type = EXCLUDED.car_type,
  car_class = EXCLUDED.car_class,
  active = EXCLUDED.active,
  state = EXCLUDED.state,
  tank_state = EXCLUDED.tank_state,
  clean_state = EXCLUDED.clean_state,
  mileage = EXCLUDED.mileage,
  tire_type = EXCLUDED.tire_type,
  tire_size = EXCLUDED.tire_size,
  last_inspection = EXCLUDED.last_inspection,
  deposit = EXCLUDED.deposit,
  price_hour = EXCLUDED.price_hour,
  hourly_deposit = EXCLUDED.hourly_deposit,
  monthly_deposit = EXCLUDED.monthly_deposit,
  investor_id = EXCLUDED.investor_id,
  purchase_price = EXCLUDED.purchase_price,
  purchase_date = EXCLUDED.purchase_date,
  age_limit = EXCLUDED.age_limit,
  driver_year_limit = EXCLUDED.driver_year_limit,
  franchise = EXCLUDED.franchise,
  max_fine = EXCLUDED.max_fine,
  repair_cost = EXCLUDED.repair_cost,
  is_air = EXCLUDED.is_air,
  climate_control = EXCLUDED.climate_control,
  parktronic = EXCLUDED.parktronic,
  parktronic_camera = EXCLUDED.parktronic_camera,
  heated_seats = EXCLUDED.heated_seats,
  audio_system = EXCLUDED.audio_system,
  usb_system = EXCLUDED.usb_system,
  rain_sensor = EXCLUDED.rain_sensor,
  engine_capacity = EXCLUDED.engine_capacity,
  number_doors = EXCLUDED.number_doors,
  tank_value = EXCLUDED.tank_value,
  pts = EXCLUDED.pts,
  registration_certificate = EXCLUDED.registration_certificate,
  body_number = EXCLUDED.body_number,
  data = EXCLUDED.data;

